services:
  - type: web
    name: my-EVNUmberPlate-api
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    plan: free